[build]
  command = "npm run build:netlify"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/downloads/*.exe"

  [headers.values]
    Content-Disposition = "attachment"
    X-Content-Type-Options = "nosniff"
